esphome:
  name: "climate-living-room"
  platform: ESP8266
  board: d1_mini

external_components:
  - source: 
      type: git
      url: https://github.com/pedobry/esphome_toshiba_suzumi
    components: [toshiba_suzumi]

logger:
  level: info

uart:
  id: uart_bus
  tx_pin: 13
  rx_pin: 15
  parity: EVEN
  baud_rate: 9600

climate:
  - platform: toshiba_suzumi
    name: living-room
    id: living_room
    uart_id: uart_bus
    outdoor_temp:        # Optional. Outdoor temperature sensor
      name: Outdoor Temp
      filters:
        # Filter out value 127 as that's what unit sends when it can's measure the outside temp.
        - filter_out: 127 
    power_select:
      name: "Power level"
    #horizontal_swing: true # Optional. Uncomment if your HVAC supports also horizontal swing
    #special_mode:          # Optional. Enable only the features your HVAC supports.
      #name: "Special mode"
      #modes:
        #- "Off"
        #- "ECO"
        #- "Hi POWER"
        #- "8 degrees"
        #- "Fireplace"

# Enable button to scan for unknown values in AC unit. This is optional.
button:
  - platform: template
    name: "Scan for unknown sensors"
    icon: "mdi:reload"
    on_press:
      then:
        - lambda: |-
            auto* controller = static_cast<toshiba_suzumi::ToshibaClimateUart*>(id(living_room));
            controller->scan();

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_enc_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "A Fallback Hotspot"
    password: "xxxxxxxxxxx"

captive_portal:
